# Generated by Django 3.1 on 2020-08-09 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csvparser', '0002_auto_20200809_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='csvparser.orders'),
        ),
    ]
